import Head from 'next/head';
import { Inter } from 'next/font/google';
import styles from './styles.module.css';
import { useRouter } from 'next/router';
import { User } from '@/models/types';
import { useState } from 'react';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const [user, setUser] = useState<User>({
    userName: '',
    password: '',
    firstName: '',
    lastName: '',
    email: '',
    phoneNumber: '',
    emailConfirmed: true,
    phoneNumberConfirmed: true,
    twoFactorEnabled: true
  });

  const router = useRouter();

  const handleChangeRegister = () => {
    router.push("/register");
  }

  const handleInputChange = (e: any) => {
    const { name, value } = e.target;
    setUser({ ...user, [name]: value });
}

  return (
    <>
      <Head>
        <title>Rede Social</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link href="https://fonts.googleapis.com/css2?family=Kanit:wght@300;400;500;700&display=swap" rel="stylesheet" />
        <link rel="icon" href="/favicon.ico" />

      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>Rede Social</h1>

        <div className={styles.directionRow}>
          <div className={styles.directionCenter}>
            <label className={styles.label} htmlFor="user">Usuário</label>
            <input id="user" type="text" placeholder="Informe seu usuário" name="userName" value={user.userName} onChange={(e) => handleInputChange(e)} className={styles.input} />
          </div>

          <div className={styles.directionCenter}>
            <label className={styles.label} htmlFor="password">Senha</label>
            <input id="password" type="password" placeholder="Digite sua senha" name="password" value={user.password} onChange={(e) => handleInputChange(e)} className={styles.input} />
          </div>
        </div>

        <div className={styles.buttonContainer}>
        <button className={styles.button} onClick={handleChangeRegister}>Login</button>
          <button className={styles.button} onClick={handleChangeRegister}>Register</button>
        </div>
      </main>
    </>
  )
}
